logger:
  endpoints:
    - endpoint:
        type: "logging"
        name: "RemoteLog"
        class: "LogMessage"
        topic: "/RemoteLog"
        QoS: 10

knowledgeIn:
  properties:

knowledgeOut:
  properties:
    - property:
        type: "data"
        name: "new_plan"
        class: "new_plan"
        topic: "/new_plan"
        QoS: 10
    - property:
        type: "data"
        name: "direction"
        class: "direction"
        topic: "/direction"
        QoS: 10

eventIn:
  properties:
    - property:
        type: "event"
        name: "anomaly"
        class: "-"
        topic: "/anomaly"
        QoS: 10
    - property:
        type: "event"
        name: "anomaly"
        class: "-"
        topic: "/anomaly"
        QoS: 10

eventOut:
  properties:

