logger:
  endpoints:
    - endpoint:
        type: "logging"
        name: "RemoteLog"
        class: "LogMessage"
        topic: "/RemoteLog"
        QoS: 10

knowledgeIn:
  properties:
    - property:
        type: "data"
        name: "laser_scan"
        class: "laser_scan"
        topic: "/laser_scan"
        QoS: 10

knowledgeOut:
  properties:

eventIn:
  properties:
    - property:
        type: "event"
        name: "laser_scan"
        class: "-"
        topic: "/laser_scan"
        QoS: 10
    - property:
        type: "event"
        name: "/Scan"
        class: "-"
        topic: "//Scan"
        QoS: 10

eventOut:
  properties:

