logger:
  endpoints:
    - endpoint:
        type: "logging"
        name: "RemoteLog"
        class: "LogMessage"
        topic: "/RemoteLog"
        QoS: 10

knowledgeIn:
  properties:
    - property:
        type: "data"
        name: "laserScan"
        class: "laserScan"
        topic: "/laserScan"
        QoS: 10

knowledgeOut:
  properties:

eventIn:
  properties:
    - property:
        type: "event"
        name: "laserScan"
        class: "-"
        topic: "/laserScan"
        QoS: 10

eventOut:
  properties:

