logger:
  endpoints:
    - endpoint:
        type: "logging"
        name: "RemoteLog"
        class: "LogMessage"
        topic: "/RemoteLog"
        QoS: 10

knowledgeIn:
  properties:
    - property:
        type: "data"
        name: "isLegit"
        class: "isLegit"
        topic: "/isLegit"
        QoS: 10
    - property:
        type: "data"
        name: "directions"
        class: "directions"
        topic: "/directions"
        QoS: 10

knowledgeOut:
  properties:

eventIn:
  properties:
    - property:
        type: "event"
        name: "new_plan"
        class: "-"
        topic: "/new_plan"
        QoS: 10
    - property:
        type: "event"
        name: "isLegit"
        class: "-"
        topic: "/isLegit"
        QoS: 10

eventOut:
  properties:
    - property:
        type: "event"
        name: "spin_config"
        class: "-"
        topic: "/spin_config"
        QoS: 10

