logger:
  endpoints:
    - endpoint:
        type: "logging"
        name: "RemoteLog"
        class: "LogMessage"
        topic: "/RemoteLog"
        QoS: 10

knowledgeIn:
  properties:
    - property:
        type: "data"
        name: "plan"
        class: "plan"
        topic: "/plan"
        QoS: 10
    - property:
        type: "data"
        name: "isLegit"
        class: "isLegit"
        topic: "/isLegit"
        QoS: 10

knowledgeOut:
  properties:
    - property:
        type: "data"
        name: "pathEstimate"
        class: "pathEstimate"
        topic: "/pathEstimate"
        QoS: 10

eventIn:
  properties:
    - property:
        type: "event"
        name: "plan"
        class: "-"
        topic: "event/plan"
        QoS: 10
    - property:
        type: "event"
        name: "isLegit"
        class: "-"
        topic: "event/isLegit"
        QoS: 10

eventOut:
  properties:
    - property:
        type: "event"
        name: "pathEstimate"
        class: "-"
        topic: "/pathEstimate"
        QoS: 10

