name:  Packages the python source code into executables using pyinstaller.

on:
  release:
    types: [created]

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'rpio.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'rpio-windows'
          options: --onefile, --name "rpio"
      - name: upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://github.com/BertVanAcker/rpio/archive/refs/tags/${{ github.ref }}/
          asset_path: ./dist
          asset_name: rpio-windows
          asset_content_type: application/zip