name:  Packages the python source code into executables using pyinstaller.

on:
  release:
    types: [created]

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'rpio.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'rpio-windows'
          options: --onefile, --name "rpio-cli"
      - name: upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ./dist/*